In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [22]:
data_profe = pd.read_excel("Data Professional Survey dataset.xlsx")

In [23]:
data_profe.head(10)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Browser,OS,City,Country,Referrer,Time Spent,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,NaN,NaN,NaN,NaN,NaN,0:00:44,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,NaN,NaN,NaN,NaN,NaN,0:01:30,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,NaN,NaN,NaN,NaN,NaN,0:02:18,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,NaN,NaN,NaN,NaN,NaN,0:02:10,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:01:51,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American
5,62a33cb6cf25554317300177,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:02:34,...,3.0,3.0,2.0,Difficult,Good Work/Life Balance,Male,33,Other (Please Specify):Republic democratic of ...,NaN,Black or African American
6,62a33cb72e54c9003e531c65,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:01:15,...,6.0,6.0,5.0,Difficult,Better Salary,Male,24,Other (Please Specify),NaN,Black or African American
7,62a33cd30f8c8599d5af0f8f,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:01:25,...,5.0,5.0,9.0,Neither easy nor difficult,Remote Work,Male,35,United States,NaN,Asian or Asian American
8,62a33cd3cf255543173001d9,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:02:10,...,4.0,5.0,5.0,Neither easy nor difficult,Better Salary,Male,35,United States,NaN,Asian or Asian American
9,62a33cd8bc6861bf3176c05f,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:01:27,...,3.0,0.0,4.0,Very Difficult,Better Salary,Male,28,United States,NaN,Hispanic or Latino

In [9]:
data_profe.dropna(axis=1,inplace=True)

In [10]:
data_profe.head(10)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,Very Difficult,Remote Work,Male,26,United States,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,0:01:30,Data Analyst,No,41k-65k,Finance,R,Very Difficult,Remote Work,Male,36,Canada,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,Very Easy,Remote Work,Female,35,Canada,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,Difficult,Better Salary,Male,44,United States,Black or African American
5,62a33cb6cf25554317300177,anonymous,6/10/2022,8:44,0:02:34,Data Analyst,Yes,0-40k,Other (Please Specify):Coworking space,Python,Difficult,Good Work/Life Balance,Male,33,Other (Please Specify):Republic democratic of ...,Black or African American
6,62a33cb72e54c9003e531c65,anonymous,6/10/2022,8:44,0:01:15,Data Scientist,Yes,0-40k,Finance,Python,Difficult,Better Salary,Male,24,Other (Please Specify),Black or African American
7,62a33cd30f8c8599d5af0f8f,anonymous,6/10/2022,8:45,0:01:25,Data Engineer,Yes,125k-150k,Other (Please Specify):Retail,Other:SQL,Neither easy nor difficult,Remote Work,Male,35,United States,Asian or Asian American
8,62a33cd3cf255543173001d9,anonymous,6/10/2022,8:45,0:02:10,Data Analyst,Yes,86k-105k,Healthcare,R,Neither easy nor difficult,Better Salary,Male,35,United States,Asian or Asian American
9,62a33cd8bc6861bf3176c05f,anonymous,6/10/2022,8:45,0:01:27,Data Analyst,Yes,41k-65k,Telecommunication,Python,Very Difficult,Better Salary,Male,28,United States,Hispanic or Latino

In [11]:
data_profe.shape

(630, 16)

In [13]:
data_profe["Q5 - Favorite Programming Language"].value_counts()

Q5 - Favorite Programming Language
Python                                                                                                                                                                                                                                                   420
R                                                                                                                                                                                                                                                        101
Other:SQL                                                                                                                                                                                                                                                 27
Other:Sql                                                                                                                                                                                                                                                 11
Other                                                                                                                                                                                                                                                      9
C/C++                                                                                                                                                                                                                                                      7
JavaScript                                                                                                                                                                                                                                                 6
Other:None                                                                                                                                                                                                                                                 6
Other:DAX                                                                                                                                                                                                                                                  5
Other:sql                                                                                                                                                                                                                                                  3
Other:SAS                                                                                                                                                                                                                                                  2
Other:SQL                                                                                                                                                                                                                                                  2
Other:I don’t know any                                                                                                                                                                                                                                     1
Other:Qlik sense script                                                                                                                                                                                                                                    1
Other:Power bi                                                                                                                                                                                                                                             1
Other:Mostly use sql but that’s not programming language..                                                                                                                                                                                                 1
Other:If SQL is categorised as a programming language then I will definitely say SQL. Since I am still learning, I can't give a definite answer in relation to the abover mentioned but for the sake of choosing I will say R then followed by python      1
Other:I don't use programming in my role                                                                                                                                                                                                                   1
Other:Excel/SQL                                                                                                                                                                                                                                            1
Other:SQL Postgres                                                                                                                                                                                                                                         1
Other:unknown                                                                                                                                                                                                                                              1
Other:Stata                                                                                                                                                                                                                                                1
Other:Vba                                                                                                                                                                                                                                                  1
Other:Excel                                                                                                                                                                                                                                                1
Other:I currently do not work with programming languages yet                                                                                                                                                                                               1
Other:Dont require                                                                                                                                                                                                                                         1
Other:Knowledge of Excel and SQL yet                                                                                                                                                                                                                       1
Other:c#                                                                                                                                                                                                                                                   1
Other:Altery                                                                                                                                                                                                                                               1
Other:i mean, i mostly work in SQL and its variants?                                                                                                                                                                                                       1
Other:Just started learning                                                                                                                                                                                                                                1
Java                                                                                                                                                                                                                                                       1
Other:NA                                                                                                                                                                                                                                                   1
Other:Mainly use Excel                                                                                                                                                                                                                                     1
Other:SQL because that is all I know really well so far.                                                                                                                                                                                                   1
Other:VBA                                                                                                                                                                                                                                                  1
Other:MATLAB                                                                                                                                                                                                                                               1
Other:Sql &  plsql                                                                                                                                                                                                                                         1
Other:Php                                                                                                                                                                                                                                                  1
Other:SAS SQL                                                                                                                                                                                                                                              1
Other:None at the moment                                                                                                                                                                                                                                   1
Other:excel                                                                                                                                                                                                                                                1
Other:I do analysis and create presentations based on datasets provided by others                                                                                                                                                                          1
Name: count, dtype: int64

In [14]:
data_profe["Q5 - Favorite Programming Language"].dropna()

0      Python
1           R
2      Python
3           R
4           R
        ...
625         R
626         R
627    Python
628    Python
629    Python
Name: Q5 - Favorite Programming Language, Length: 630, dtype: object

In [20]:
data_profe.head(10)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,Very Difficult,Remote Work,Male,26,United States,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,0:01:30,Data Analyst,No,41k-65k,Finance,R,Very Difficult,Remote Work,Male,36,Canada,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,Very Easy,Remote Work,Female,35,Canada,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,Difficult,Better Salary,Male,44,United States,Black or African American
5,62a33cb6cf25554317300177,anonymous,6/10/2022,8:44,0:02:34,Data Analyst,Yes,0-40k,Other (Please Specify):Coworking space,Python,Difficult,Good Work/Life Balance,Male,33,Other (Please Specify):Republic democratic of ...,Black or African American
6,62a33cb72e54c9003e531c65,anonymous,6/10/2022,8:44,0:01:15,Data Scientist,Yes,0-40k,Finance,Python,Difficult,Better Salary,Male,24,Other (Please Specify),Black or African American
7,62a33cd30f8c8599d5af0f8f,anonymous,6/10/2022,8:45,0:01:25,Data Engineer,Yes,125k-150k,Other (Please Specify):Retail,Other:SQL,Neither easy nor difficult,Remote Work,Male,35,United States,Asian or Asian American
8,62a33cd3cf255543173001d9,anonymous,6/10/2022,8:45,0:02:10,Data Analyst,Yes,86k-105k,Healthcare,R,Neither easy nor difficult,Better Salary,Male,35,United States,Asian or Asian American
9,62a33cd8bc6861bf3176c05f,anonymous,6/10/2022,8:45,0:01:27,Data Analyst,Yes,41k-65k,Telecommunication,Python,Very Difficult,Better Salary,Male,28,United States,Hispanic or Latino