In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-2.3.0-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\megha agarwal\onedrive\desktop\kmeans cluster\.venv\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\megha agarwal\onedrive\desktop\kmeans cluster\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\megha agarwal\onedrive\desktop\kmeans cluster\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\megha agarwal\onedrive\desktop\kmeans cluster\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\megha agarwal\onedrive\desktop\kmeans cluster\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.0-cp313-cp313-win_amd64.whl (11.0 MB)
Installing collected packages: pandas
Successfully installed pandas-2.3.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("SCFP2019.csv.gz")

In [16]:
df

,YY1,Y1,WGT,HHSEX,AGE,AGECL,EDUC,EDCL,MARRIED,KIDS,...,NWCAT,INCCAT,ASSETCAT,NINCCAT,NINC2CAT,NWPCTLECAT,INCPCTLECAT,NINCPCTLECAT,INCQRTCAT,NINCQRTCAT
0,1,11,6119.779308,2,75,6,12,4,2,0,...,5,3,6,3,2,10,6,6,3,3
1,1,12,4712.374912,2,75,6,12,4,2,0,...,5,3,6,3,1,10,5,5,2,2
2,1,13,5145.224455,2,75,6,12,4,2,0,...,5,3,6,3,1,10,5,5,2,2
3,1,14,5297.663412,2,75,6,12,4,2,0,...,5,2,6,2,1,10,4,4,2,2
4,1,15,4761.812371,2,75,6,12,4,2,0,...,5,3,6,3,1,10,5,5,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28880,5813,58131,667.098300,1,51,3,5,1,1,0,...,5,6,6,6,3,11,11,11,4,4
28881,5813,58132,678.821856,1,51,3,5,1,1,0,...,5,6,6,6,3,11,11,11,4,4
28882,5813,58133,640.908142,1,51,3,5,1,1,0,...,5,6,6,6,3,11,11,11,4,4
28883,5813,58134,665.152072,1,51,3,5,1,1,0,...,5,6,6,6,3,11,11,11,4,4
28884,5813,58135,662.401934,1,51,3,5,1,1,0,...,5,6,6,6,3,11,11,11,4,4

In [10]:
df2=pd.DataFrame(df.columns)

In [13]:
df.to_excel("output.xlsx")

ModuleNotFoundError: No module named 'openpyxl'

In [14]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000012C9DBE2270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/openpyxl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000012C9DBD9BD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/openpyxl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000012C9DBD9E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/openpyxl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000012C9DBDA0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/openpyxl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000012C9DBDA350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/openpyxl/
ERROR: Could not find a version that satisfies the requirement openpyxl (from versions: none)
ERROR: No matching distribution found for openpyxl

In [15]:
df.shape

(28885, 357)